### ISSUE TITLE
Downloading ptdb dataset fails

### ISSUE THREAD

**Issue by anthonio9** [maxrmorrison/torchutil#2]
This is related to the official `penn` repository. Downloading the dataset fails, whilst *mdb* dataset downloads without any errors, downloading *ptdb* throws an error that's `torchutil` related, last few lines of the error below:

```sh
 % python3.10 -m penn.data.download --datasets "ptdb"
.
.
.
  File "~/.local/lib/python3.10/site-packages/torchutil/download.py", line 62, in zip
    file(url, tmp)
  File "~/.local/lib/python3.10/site-packages/torchutil/download.py", line 23, in file
    with open(path, 'wb') as fstream:
TypeError: expected str, bytes or os.PathLike object, not _TemporaryFileWrapper
```
I've found a fix for the issue, as the `file` function from `torchutil.download.py` expects the path to be string, bytes or os.PathLike, extracting the name from the `NamedTemporaryFile` was enough:

```diff
diff --git a/torchutil/download.py b/torchutil/download.py
index 31538e8..5bc53f6 100644
--- a/torchutil/download.py
+++ b/torchutil/download.py
@@ -59,6 +59,6 @@ def zip(url: 'str', path: Union[str, bytes, os.PathLike]):
         path - The location to save results
     """
     with tempfile.NamedTemporaryFile() as tmp:
-        file(url, tmp)
+        file(url, tmp.name)
         with zipfile.ZipFile(tmp, 'r') as zfile:
             zfile.extractall(path)
```

will be posting a pull request with this change soon.

Thanks for the great tool!

**Comment by maxrmorrison** [comment]
Thanks for the fix! I'm working updates to the notification system and the `paths` submodule. I'll push a new version that includes your fix once testing for those updates is done--most likely tonight/tomorrow.

**Comment by anthonio9** [comment]
Sure, thanks a lot again, amazing work!
